/**
 * data.js - Banco de Dados do Catálogo
 * Total: 82 Produtos
 */

const database = {
  categorias: [
    {
      id: "cat_graos",
      nome: "Cafés e Métodos",
      produtos: [
        {
          id: 1,
          nome: "Café Mió Gourmet",
          preco: 9.9,
          vazio: false,
          tags: ["frutado", "suave", "arabica", "mio"],
          desc: "Notas frutadas e acidez delicada.",
        },
        {
          id: 2,
          nome: "Café Bão Clássico",
          preco: 8.9,
          vazio: false,
          tags: ["mel", "tradicional", "bao"],
          desc: "Notas de mel e acidez cítrica.",
        },
        {
          id: 3,
          nome: "Café Moca Raro",
          preco: 11.9,
          vazio: false,
          tags: ["caramelo", "chocolate", "mooca"],
          desc: "Grão raro, encorpado e doce.",
        },
        {
          id: 4,
          nome: "Microlote Especial",
          preco: 11.9,
          vazio: false,
          tags: ["taca", "pontuacao", "exclusivo"],
          desc: "Notas complexas servidas na taça.",
        },
        {
          id: 5,
          nome: "Upgrade Double Shot",
          preco: 3.0,
          vazio: false,
          tags: ["dobro", "dose", "extra"],
          desc: "Dobre a dose de cafeína do seu café.",
        },
        {
          id: 6,
          nome: "Método Hario V60",
          preco: 12.0,
          vazio: false,
          tags: ["coado", "v60"],
          desc: "Preparo limpo que ressalta a acidez.",
        },
        {
          id: 7,
          nome: "Método Chemex",
          preco: 14.0,
          vazio: false,
          tags: ["filtro", "puro"],
          desc: "Design e pureza no sabor.",
        },
        {
          id: 8,
          nome: "Método Aeropress",
          preco: 12.0,
          vazio: false,
          tags: ["pressao", "corpo"],
          desc: "Extração por pressão, sabor intenso.",
        },
        {
          id: 9,
          nome: "Prensa Francesa",
          preco: 12.0,
          vazio: false,
          tags: ["french", "oleos"],
          desc: "Preserva os óleos naturais do café.",
        },
        {
          id: 10,
          nome: "Método Clever",
          preco: 12.0,
          vazio: false,
          tags: ["infusao", "clever"],
          desc: "Equilíbrio perfeito entre imersão e filtro.",
        },
        {
          id: 11,
          nome: "Espresso Simples",
          preco: 8.9,
          vazio: false,
          tags: ["curto", "puro"],
          desc: "Extração clássica de 30ml.",
        },
        {
          id: 12,
          nome: "Espresso Duplo",
          preco: 11.9,
          vazio: false,
          tags: ["doppio", "forte"],
          desc: "O dobro de energia para o seu dia.",
        },
        {
          id: 13,
          nome: "Degustação Comparativa",
          preco: 15.0,
          vazio: true,
          tags: ["experiencia", "dois"],
          desc: "Compare grão especial vs comum.",
        },
      ],
    },
    {
      id: "cat_quentes",
      nome: "Bebidas Quentes",
      produtos: [
        {
          id: 14,
          nome: "Cappuccino Tradicional",
          preco: 11.9,
          vazio: false,
          tags: ["leite", "canela"],
          desc: "Receita clássica com espuma cremosa.",
        },
        {
          id: 15,
          nome: "Cappuccino Avelã",
          preco: 11.9,
          vazio: false,
          tags: ["nutella", "doce"],
          desc: "Toque de avelã para adoçar a pausa.",
        },
        {
          id: 16,
          nome: "Cappuccino Light",
          preco: 11.9,
          vazio: false,
          tags: ["fit", "dieta"],
          desc: "Sabor intenso com baixas calorias.",
        },
        {
          id: 17,
          nome: "Chocolatíssimo Quente",
          preco: 18.9,
          vazio: false,
          tags: ["pacoca", "chocolate"],
          desc: "Chocolate cremoso com paçoca artesanal.",
        },
        {
          id: 18,
          nome: "Chocomalow Quente",
          preco: 18.9,
          vazio: false,
          tags: ["marshmallow", "fogo"],
          desc: "Chocolate quente com marshmallows tostados.",
        },
        {
          id: 19,
          nome: "Cookieccino da Casa",
          preco: 19.9,
          vazio: false,
          tags: ["cookie", "borda", "biscoito"],
          desc: "Borda de cookie com creme de avelã.",
        },
        {
          id: 20,
          nome: "Latte Doce de Leite",
          preco: 13.9,
          vazio: false,
          tags: ["mineiro", "doce"],
          desc: "Café com leite e o legítimo doce de leite.",
        },
        {
          id: 21,
          nome: "Chocolate Quente Puro",
          preco: 12.9,
          vazio: false,
          tags: ["cacau", "inverno"],
          desc: "Cremosidade absoluta em cada gole.",
        },
        {
          id: 22,
          nome: "Chai Latte Indiano",
          preco: 11.9,
          vazio: false,
          tags: ["cha", "especiarias"],
          desc: "Mix de especiarias e leite vaporizado.",
        },
        {
          id: 23,
          nome: "Cappuccino Italiano Real",
          preco: 11.9,
          vazio: false,
          tags: ["vaporizado", "classico"],
          desc: "Foco na textura do leite e do espresso.",
        },
      ],
    },
    {
      id: "cat_geladas",
      nome: "Bebidas Refrescantes",
      produtos: [
        {
          id: 24,
          nome: "Iced Cappuccino Tradicional",
          preco: 16.9,
          vazio: false,
          tags: ["gelado", "frio"],
          desc: "O clássico agora na versão Iced.",
        },
        {
          id: 25,
          nome: "Iced Cappuccino Fit",
          preco: 18.9,
          vazio: false,
          tags: ["light", "gelado"],
          desc: "Refresco sem culpa.",
        },
        {
          id: 26,
          nome: "Bebida Julieta e Romeu",
          preco: 16.9,
          vazio: false,
          tags: ["goiabada", "queijo"],
          desc: "Goiabada cremosa batida com queijo.",
        },
        {
          id: 27,
          nome: "Cappuccinoca Gelado",
          preco: 18.9,
          vazio: false,
          tags: ["pacoca", "amendoim"],
          desc: "Mistura refrescante de café e paçoca.",
        },
        {
          id: 28,
          nome: "Frapê de Frutas",
          preco: 16.9,
          vazio: false,
          tags: ["gelo", "batido"],
          desc: "Escolha seu sabor favorito: Morango ou Amora.",
        },
        {
          id: 29,
          nome: "Soda Italiana",
          preco: 12.9,
          vazio: false,
          tags: ["gas", "xarope"],
          desc: "Água gaseificada com xaropes artesanais.",
        },
        {
          id: 30,
          nome: "Chá Gelado da Casa",
          preco: 12.9,
          vazio: false,
          tags: ["matte", "limao"],
          desc: "Natural e refrescante.",
        },
        {
          id: 31,
          nome: "Affogato Al Café",
          preco: 15.9,
          vazio: false,
          tags: ["sorvete", "espresso"],
          desc: "Sorvete de creme afogado no café quente.",
        },
        {
          id: 32,
          nome: "Limonada do Bosque",
          preco: 18.9,
          vazio: false,
          tags: ["limao", "frutas vermelhas"],
          desc: "Limão siciliano com calda de frutas.",
        },
        {
          id: 33,
          nome: "Iced Chocomalow",
          preco: 18.9,
          vazio: false,
          tags: ["gelado", "marshmallow"],
          desc: "Chocolate gelado com marshmallows.",
        },
      ],
    },
    {
      id: "cat_assados",
      nome: "Assados e Mineirices",
      produtos: [
        {
          id: 34,
          nome: "Pão de Queijo Individual",
          preco: 8.9,
          vazio: false,
          tags: ["pdq", "grande"],
          desc: "Unidade grande de pão de queijo mineiro.",
        },
        {
          id: 35,
          nome: "Cesta Pão de Queijo (6)",
          preco: 18.9,
          vazio: false,
          tags: ["porcao", "cesta"],
          desc: "Ideal para compartilhar no café.",
        },
        {
          id: 36,
          nome: "Cesta Pão de Queijo (12)",
          preco: 33.9,
          vazio: false,
          tags: ["familia", "porcao"],
          desc: "A alegria da mesa completa.",
        },
        {
          id: 37,
          nome: "PDQ Congelado 1kg",
          preco: 45.0,
          vazio: true,
          tags: ["levar", "casa"],
          desc: "Leve o sabor da cafeteria para sua casa.",
        },
        {
          id: 38,
          nome: "Mini Coxinha (4 unidades)",
          preco: 10.9,
          vazio: false,
          tags: ["salgado", "frango"],
          desc: "Massa fininha e recheio cremoso.",
        },
        {
          id: 39,
          nome: "Mini Coxinha (8 unidades)",
          preco: 19.9,
          vazio: false,
          tags: ["porcao", "lanche"],
          desc: "Porção generosa de coxinhas.",
        },
        {
          id: 40,
          nome: "Folhado Amanteigado",
          preco: 11.9,
          vazio: false,
          tags: ["folhado", "frances"],
          desc: "Massa amanteigada e crocante.",
        },
        {
          id: 41,
          nome: "Quiche do Dia",
          preco: 12.9,
          vazio: false,
          tags: ["quiche", "torta"],
          desc: "Recheios selecionados do dia.",
        },
        {
          id: 42,
          nome: "Mineirin Escondidinho",
          preco: 24.9,
          vazio: false,
          tags: ["batata", "queijo", "quente"],
          desc: "Escondidinho gratinado na hora.",
        },
        {
          id: 43,
          nome: "Caldinho de Vó",
          preco: 15.9,
          vazio: false,
          tags: ["sopa", "caldo"],
          desc: "Conforto em forma de sopa.",
        },
      ],
    },
    {
      id: "cat_sanduiches",
      nome: "Sanduíches e Lanches",
      produtos: [
        {
          id: 44,
          nome: "Waffle do Chef Salgado",
          preco: 27.9,
          vazio: false,
          tags: ["waffle", "peru"],
          desc: "Peito de peru, muçarela e requeijão.",
        },
        {
          id: 45,
          nome: "Hot Dog Mineiro",
          preco: 23.9,
          vazio: false,
          tags: ["cachorro", "goiabada"],
          desc: "Baguete de pão de queijo e barbecue de goiabada.",
        },
        {
          id: 46,
          nome: "Montanhas de Minas",
          preco: 27.9,
          vazio: false,
          tags: ["frango", "waffle"],
          desc: "Waffle de pão de queijo com frango.",
        },
        {
          id: 47,
          nome: "Divino Croissant",
          preco: 28.9,
          vazio: false,
          tags: ["croissant", "doce"],
          desc: "Frango, requeijão e geleia de abacaxi.",
        },
        {
          id: 48,
          nome: "Frango Especial Croissant",
          preco: 27.9,
          vazio: false,
          tags: ["frango", "queijo"],
          desc: "O clássico croissant recheado.",
        },
        {
          id: 49,
          nome: "Pernil da Roça no Pão",
          preco: 24.9,
          vazio: false,
          tags: ["pernil", "baguete"],
          desc: "Pernil desfiado suculento.",
        },
        {
          id: 50,
          nome: "Tropical Queijo Minas",
          preco: 25.9,
          vazio: false,
          tags: ["saudavel", "minas"],
          desc: "Leveza com queijo minas frescal.",
        },
        {
          id: 51,
          nome: "Tropical de Frango",
          preco: 25.9,
          vazio: false,
          tags: ["saudavel", "frango"],
          desc: "Frango com toque de manga.",
        },
        {
          id: 52,
          nome: "PDQ Recheado Minas",
          preco: 17.9,
          vazio: false,
          tags: ["pdq", "recheio"],
          desc: "Pão de queijo recheado na hora.",
        },
        {
          id: 53,
          nome: "Waffle PDQ Recheado",
          preco: 25.9,
          vazio: false,
          tags: ["waffle", "recheio"],
          desc: "A massa do pão de queijo em formato waffle.",
        },
        {
          id: 54,
          nome: "Melaço Mineiro",
          preco: 23.9,
          vazio: false,
          tags: ["doce", "salgado"],
          desc: "Waffle, requeijão e melaço.",
        },
        {
          id: 55,
          nome: "Misto Quente Padrão",
          preco: 15.9,
          vazio: false,
          tags: ["misto", "presunto"],
          desc: "O clássico do café da manhã.",
        },
        {
          id: 56,
          nome: "Queijo Quente Especial",
          preco: 17.9,
          vazio: false,
          tags: ["queijo", "derretido"],
          desc: "Blend de queijos derretidos.",
        },
        {
          id: 57,
          nome: "Pão na Chapa",
          preco: 14.9,
          vazio: false,
          tags: ["manteiga", "pao"],
          desc: "Crocante e amanteigado.",
        },
      ],
    },
    {
      id: "cat_sobremesas",
      nome: "Doces e Sobremesas",
      produtos: [
        {
          id: 58,
          nome: "Banowaffle Doce",
          preco: 18.9,
          vazio: false,
          tags: ["banana", "doce de leite"],
          desc: "Banana, doce de leite e chantilly.",
        },
        {
          id: 59,
          nome: "Pãozinho de Chuva (6)",
          preco: 16.9,
          vazio: false,
          tags: ["canela", "doce de leite"],
          desc: "Mini pães de queijo com canela.",
        },
        {
          id: 60,
          nome: "Sobremesa Tu Di Bão",
          preco: 18.9,
          vazio: false,
          tags: ["sorvete", "chocolate"],
          desc: "Sorvete, calda quente e paçoca.",
        },
        {
          id: 61,
          nome: "Samba de Limão Torta",
          preco: 19.9,
          vazio: false,
          tags: ["limao", "torta"],
          desc: "Desconstrução de torta de limão.",
        },
        {
          id: 62,
          nome: "Waffle Personalizado",
          preco: 19.9,
          vazio: false,
          tags: ["escolha", "calda"],
          desc: "Monte seu waffle com suas caldas favoritas.",
        },
        {
          id: 63,
          nome: "Waffle com Sorvete",
          preco: 16.9,
          vazio: false,
          tags: ["gelado", "waffle"],
          desc: "Waffle quentinho com sorvete de creme.",
        },
        {
          id: 64,
          nome: "Cookie com Gotas",
          preco: 8.9,
          vazio: false,
          tags: ["baunilha", "cookies"],
          desc: "Cookie crocante por fora e macio por dentro.",
        },
        {
          id: 65,
          nome: "Brownie com Sorvete",
          preco: 17.9,
          vazio: false,
          tags: ["brownie", "chocolate"],
          desc: "Fatia de brownie denso e chocolatudo.",
        },
        {
          id: 66,
          nome: "Tortas do Dia",
          preco: 14.9,
          vazio: false,
          tags: ["fatia", "torta"],
          desc: "Consulte nossos sabores sazonais.",
        },
        {
          id: 67,
          nome: "Donuts Recheados",
          preco: 13.9,
          vazio: false,
          tags: ["rosquinha", "doce"],
          desc: "Avelã ou Frutas Vermelhas.",
        },
        {
          id: 68,
          nome: "Cheesecake Clássica",
          preco: 16.9,
          vazio: false,
          tags: ["frutas", "calda"],
          desc: "Cremosa com calda de frutas do bosque.",
        },
        {
          id: 69,
          nome: "Bolo Caseiro de Vó",
          preco: 10.9,
          vazio: false,
          tags: ["vovo", "fatia"],
          desc: "Bolo de fubá ou castanhas.",
        },
        {
          id: 70,
          nome: "Bolo Chocolatudo 60%",
          preco: 17.9,
          vazio: false,
          tags: ["cacau", "chocolate"],
          desc: "Para amantes de chocolate intenso.",
        },
      ],
    },
    {
      id: "cat_emporio",
      nome: "Empório e Presentes",
      produtos: [
        {
          id: 71,
          nome: "Café Bão 250g",
          preco: 53.9,
          vazio: false,
          tags: ["pacote", "grao"],
          desc: "Leve o clássico para casa.",
        },
        {
          id: 72,
          nome: "Café Mió 250g",
          preco: 55.9,
          vazio: false,
          tags: ["pacote", "premium"],
          desc: "Grãos selecionados em embalagem especial.",
        },
        {
          id: 73,
          nome: "Café Moca 250g",
          preco: 68.9,
          vazio: false,
          tags: ["raridade", "pacote"],
          desc: "Grão moca para paladares exigentes.",
        },
        {
          id: 74,
          nome: "Café Microlote 250g",
          preco: 74.9,
          vazio: false,
          tags: ["exclusivo", "grao"],
          desc: "O melhor da nossa safra.",
        },
        {
          id: 75,
          nome: "Drip Coffee Box",
          preco: 45.9,
          vazio: false,
          tags: ["filtro", "individual"],
          desc: "Café especial em qualquer lugar.",
        },
        {
          id: 76,
          nome: "Creme de Goiaba Pote",
          preco: 22.0,
          vazio: false,
          tags: ["doce", "pote"],
          desc: "Geleia artesanal de goiaba.",
        },
        {
          id: 77,
          nome: "Cocada Cremosa Pote",
          preco: 24.0,
          vazio: false,
          tags: ["coco", "doce"],
          desc: "Cocada mineira de colher.",
        },
        {
          id: 78,
          nome: "Doce de Leite c/ Café",
          preco: 26.0,
          vazio: false,
          tags: ["mistura", "mineiro"],
          desc: "A união perfeita de Minas.",
        },
      ],
    },
    {
      id: "cat_adicionais",
      nome: "Adicionais",
      produtos: [
        {
          id: 79,
          nome: "Extra Chantilly",
          preco: 4.0,
          vazio: false,
          tags: ["creme", "extra"],
          desc: "Dose extra de chantilly artesanal.",
        },
        {
          id: 80,
          nome: "Extra Doce de Leite",
          preco: 4.0,
          vazio: false,
          tags: ["doce", "porcao"],
          desc: "Para os amantes de açúcar.",
        },
        {
          id: 81,
          nome: "Extra Creme Avelã",
          preco: 5.0,
          vazio: false,
          tags: ["nutella", "chocolate"],
          desc: "Adicione mais sabor ao seu pedido.",
        },
        {
          id: 82,
          nome: "Troca Leite Vegetal",
          preco: 6.0,
          vazio: false,
          tags: ["vegano", "fit"],
          desc: "Substitua por leite de aveia ou coco.",
        },
      ],
    },
  ],
};
