/**
 * database.js - Repositório de Dados Consolidado
 * Imagens mapeadas conforme diretório ./assets/
 */

const DATA = {
  categorias: [
    { id: "todos", nome: "Todos", icone: "📋" },
    { id: "lancamentos", nome: "Lançamentos", icone: "🔥" },
    { id: "tradicionais", nome: "Pastéis Tradicionais", icone: "🥟" },
    { id: "especiais", nome: "Pastéis Especiais", icone: "⭐" },
    { id: "bebidas", nome: "Cana e Bebidas", icone: "🥤" },
  ],
  heroDestaques: [
    {
      id: 9,
      nome: "Pastel da Casa",
      ingrediente: "O Gigante da Região",
      img: "./assets/pastel-e-caldo-1.jpg",
    },
    {
      id: 25,
      nome: "Combo Supremo",
      ingrediente: "Pastel + Caldo 500ml",
      img: "./assets/pastel-e-caldo-3.jpg",
    },
    {
      id: 40,
      nome: "Cana Pura",
      ingrediente: "Moída na Hora",
      img: "./assets/caldo-1.jpg",
    },
  ],
  produtos: [
    // --- 1. TRADICIONAIS (Pastéis 1 a 5) ---
    {
      id: 1,
      categoria: "tradicionais",
      nome: "Pastel de Carne",
      preco: 7.99,
      img: "./assets/pastel-1.jpg",
      lancamento: false,
    },
    {
      id: 2,
      categoria: "tradicionais",
      nome: "Pastel de Queijo",
      preco: 7.99,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 3,
      categoria: "tradicionais",
      nome: "Pastel de Frango",
      preco: 7.99,
      img: "./assets/pastel-3.jpg",
      lancamento: true,
    },
    {
      id: 4,
      categoria: "tradicionais",
      nome: "Pastel de Calabresa",
      preco: 7.99,
      img: "./assets/pastel-4.jpg",
      lancamento: false,
    },
    {
      id: 5,
      categoria: "tradicionais",
      nome: "Presunto c/ Queijo",
      preco: 7.99,
      img: "./assets/pastel-5.jpg",
      lancamento: false,
    },
    {
      id: 13,
      categoria: "tradicionais",
      nome: "Carne com Ovo",
      preco: 8.5,
      img: "./assets/pastel-1.jpg",
      lancamento: false,
    },
    {
      id: 14,
      categoria: "tradicionais",
      nome: "Frango com Milho",
      preco: 8.5,
      img: "./assets/pastel-3.jpg",
      lancamento: false,
    },
    {
      id: 15,
      categoria: "tradicionais",
      nome: "Bauru Tradicional",
      preco: 8.5,
      img: "./assets/pastel-4.jpg",
      lancamento: false,
    },
    {
      id: 16,
      categoria: "tradicionais",
      nome: "Calabresa com Queijo",
      preco: 8.99,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 17,
      categoria: "tradicionais",
      nome: "Milho com Queijo",
      preco: 8.5,
      img: "./assets/pastel-5.jpg",
      lancamento: false,
    },
    {
      id: 18,
      categoria: "tradicionais",
      nome: "Queijo com Orégano",
      preco: 7.99,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 19,
      categoria: "tradicionais",
      nome: "Escarola com Queijo",
      preco: 8.5,
      img: "./assets/pastel-1.jpg",
      lancamento: false,
    },
    {
      id: 20,
      categoria: "tradicionais",
      nome: "Pastel Hot Dog",
      preco: 8.99,
      img: "./assets/pastel-4.jpg",
      lancamento: true,
    },
    {
      id: 21,
      categoria: "tradicionais",
      nome: "Sabor Pizza",
      preco: 8.5,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 22,
      categoria: "tradicionais",
      nome: "Carne com Milho",
      preco: 8.5,
      img: "./assets/pastel-3.jpg",
      lancamento: false,
    },

    // --- 2. ESPECIAIS (Combos e Recheios Premium) ---
    {
      id: 6,
      categoria: "especiais",
      nome: "Frango c/ Catupiry",
      preco: 11.99,
      img: "./assets/pastel-e-caldo-1.jpg",
      lancamento: true,
    },
    {
      id: 7,
      categoria: "especiais",
      nome: "Carne c/ Queijo",
      preco: 11.99,
      img: "./assets/pastel-e-caldo-2.jpg",
      lancamento: false,
    },
    {
      id: 8,
      categoria: "especiais",
      nome: "Queijo c/ Goiabada",
      preco: 11.99,
      img: "./assets/pastel-e-caldo-3.jpg",
      lancamento: true,
    },
    {
      id: 9,
      categoria: "especiais",
      nome: "Pastel da Casa",
      preco: 29.99,
      img: "./assets/pastel-e-caldo-1.jpg",
      lancamento: false,
    },
    {
      id: 23,
      categoria: "especiais",
      nome: "Carne Seca c/ Abóbora",
      preco: 14.5,
      img: "./assets/pastel-1.jpg",
      lancamento: true,
    },
    {
      id: 24,
      categoria: "especiais",
      nome: "Bacalhau do Porto",
      preco: 18.9,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 25,
      categoria: "especiais",
      nome: "Nutella c/ Morango",
      preco: 15.0,
      img: "./assets/pastel-4.jpg",
      lancamento: true,
    },
    {
      id: 26,
      categoria: "especiais",
      nome: "Quatro Queijos",
      preco: 13.99,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 27,
      categoria: "especiais",
      nome: "Camarão Cream Cheese",
      preco: 19.99,
      img: "./assets/pastel-e-caldo-2.jpg",
      lancamento: true,
    },
    {
      id: 28,
      categoria: "especiais",
      nome: "Vegano: Palmito",
      preco: 12.99,
      img: "./assets/pastel-1.jpg",
      lancamento: false,
    },
    {
      id: 29,
      categoria: "especiais",
      nome: "Lombo c/ Cheddar",
      preco: 13.5,
      img: "./assets/pastel-4.jpg",
      lancamento: false,
    },
    {
      id: 30,
      categoria: "especiais",
      nome: "Doce Banoffee",
      preco: 12.5,
      img: "./assets/pastel-5.jpg",
      lancamento: true,
    },
    {
      id: 31,
      categoria: "especiais",
      nome: "Strogonoff Carne",
      preco: 14.0,
      img: "./assets/pastel-3.jpg",
      lancamento: false,
    },
    {
      id: 32,
      categoria: "especiais",
      nome: "Moda Portuguesa",
      preco: 13.5,
      img: "./assets/pastel-2.jpg",
      lancamento: false,
    },
    {
      id: 33,
      categoria: "especiais",
      nome: "Costela Desfiada",
      preco: 16.9,
      img: "./assets/pastel-e-caldo-1.jpg",
      lancamento: true,
    },

    // --- 3. BEBIDAS NATURAIS (Foco: Cana, Coco e Água) ---
    {
      id: 10,
      categoria: "bebidas",
      nome: "Cana Pura 300ml",
      preco: 6.0,
      img: "./assets/caldo-1.jpg",
      lancamento: false,
    },
    {
      id: 11,
      categoria: "bebidas",
      nome: "Cana Pura 500ml",
      preco: 8.0,
      img: "./assets/caldo-2.jpg",
      lancamento: false,
    },
    {
      id: 12,
      categoria: "bebidas",
      nome: "Água de Coco 300ml",
      preco: 7.0,
      img: "./assets/caldo-3.jpg",
      lancamento: true,
    },
    {
      id: 34,
      categoria: "bebidas",
      nome: "Água de Coco 500ml",
      preco: 10.0,
      img: "./assets/caldo-4.jpg",
      lancamento: false,
    },
    {
      id: 35,
      categoria: "bebidas",
      nome: "Cana com Coco 500ml",
      preco: 11.0,
      img: "./assets/caldo-1.jpg",
      lancamento: true,
    },
    {
      id: 36,
      categoria: "bebidas",
      nome: "Garrafa de Coco 1L",
      preco: 18.0,
      img: "./assets/caldo-2.jpg",
      lancamento: false,
    },
    {
      id: 37,
      categoria: "bebidas",
      nome: "Água Mineral 500ml",
      preco: 3.0,
      img: "./assets/caldo-5.jpg",
      lancamento: false,
    },
    {
      id: 38,
      categoria: "bebidas",
      nome: "Água com Gás 500ml",
      preco: 3.5,
      img: "./assets/caldo-5.jpg",
      lancamento: false,
    },
    {
      id: 39,
      categoria: "bebidas",
      nome: "Mix Cana & Coco 300ml",
      preco: 8.5,
      img: "./assets/caldo-3.jpg",
      lancamento: false,
    },
    {
      id: 40,
      categoria: "bebidas",
      nome: "Garrafa Cana 1.5L",
      preco: 22.0,
      img: "./assets/caldo-2.jpg",
      lancamento: true,
    },
    {
      id: 41,
      categoria: "bebidas",
      nome: "Cana com Gelo e Limão",
      preco: 8.5,
      img: "./assets/caldo-4.jpg",
      lancamento: false,
    },
    {
      id: 42,
      categoria: "bebidas",
      nome: "Combo Hidratação (Cana+Coco)",
      preco: 15.0,
      img: "./assets/caldo-1.jpg",
      lancamento: true,
    },
  ],
};
