/*
 * dados.js · Tech Educa (School).
 * Catálogo fictício de cursos e artigos usado por todas as páginas.
 * Para incluir um curso ou artigo, basta acrescentar um objeto nas listas.
 */
const CURSOS = [
  {
    id: "front-end",
    titulo: "Front-end do zero ao deploy",
    area: "Front-end",
    nivel: "Iniciante",
    horas: 80,
    preco: 1290,
    img: "./images/c1.jpg",
    resumo: "HTML semântico, CSS moderno, JavaScript e publicação do seu primeiro site responsivo.",
    ementa: [
      ["HTML semântico e acessibilidade", "Estrutura de páginas, formulários acessíveis e boas práticas de SEO."],
      ["CSS moderno", "Flexbox, Grid, variáveis e layouts responsivos para qualquer tela."],
      ["JavaScript essencial", "DOM, eventos, fetch e validação de formulários com mensagens claras."],
      ["Projeto final", "Landing page publicada no GitHub Pages com revisão da mentoria."],
    ],
  },
  {
    id: "css-avancado",
    titulo: "CSS avançado e design systems",
    area: "Front-end",
    nivel: "Intermediário",
    horas: 40,
    preco: 790,
    img: "./images/c2.jpg",
    resumo: "Arquitetura de estilos, tokens, componentes reutilizáveis e animações com propósito.",
    ementa: [
      ["Arquitetura de CSS", "BEM, camadas e organização de estilos em projetos grandes."],
      ["Tokens e temas", "Cores, tipografia e espaçamentos como variáveis, com tema escuro."],
      ["Componentes", "Botões, cartões, modais e formulários prontos para reutilizar."],
      ["Movimento", "Transições acessíveis que respeitam a preferência de redução de movimento."],
    ],
  },
  {
    id: "python-dados",
    titulo: "Dados com Python",
    area: "Dados",
    nivel: "Iniciante",
    horas: 60,
    preco: 1090,
    img: "./images/c3.jpg",
    resumo: "Python, pandas e visualização para transformar planilhas em decisões.",
    ementa: [
      ["Fundamentos de Python", "Tipos, funções, listas e dicionários com exercícios guiados."],
      ["Pandas na prática", "Limpeza, junção e agrupamento de dados reais."],
      ["Visualização", "Gráficos claros com matplotlib e boas práticas de storytelling."],
      ["Projeto final", "Painel de indicadores publicado com relatório de conclusões."],
    ],
  },
  {
    id: "node",
    titulo: "Back-end com Node.js",
    area: "Back-end",
    nivel: "Intermediário",
    horas: 70,
    preco: 1390,
    img: "./images/c4.jpg",
    resumo: "APIs REST com Node.js, banco de dados, autenticação e testes automatizados.",
    ementa: [
      ["Node.js e npm", "Módulos, scripts e organização de um projeto profissional."],
      ["APIs REST", "Rotas, validação de entrada e respostas de erro padronizadas."],
      ["Banco de dados", "Modelagem, consultas e migrações com PostgreSQL."],
      ["Qualidade", "Testes automatizados, variáveis de ambiente e deploy."],
    ],
  },
  {
    id: "ux-ui",
    titulo: "UX/UI Design para produtos digitais",
    area: "UX/UI",
    nivel: "Iniciante",
    horas: 50,
    preco: 990,
    img: "./images/c5.jpg",
    resumo: "Pesquisa, fluxos, protótipos no Figma e testes de usabilidade com usuários reais.",
    ementa: [
      ["Pesquisa com usuários", "Entrevistas, personas e mapa de jornada."],
      ["Arquitetura e fluxos", "Organização de conteúdo e fluxos de tarefas."],
      ["Interface no Figma", "Grids, componentes e protótipos navegáveis."],
      ["Teste de usabilidade", "Roteiro, condução do teste e plano de melhorias."],
    ],
  },
  {
    id: "angular",
    titulo: "Angular para aplicações corporativas",
    area: "Front-end",
    nivel: "Avançado",
    horas: 60,
    preco: 1490,
    img: "./images/c6.jpg",
    resumo: "Componentes, serviços, rotas e formulários reativos em aplicações de grande porte.",
    ementa: [
      ["Fundamentos do Angular", "Componentes, templates e injeção de dependência."],
      ["Rotas e módulos", "Carregamento sob demanda e guarda de rotas."],
      ["Formulários reativos", "Validação síncrona e assíncrona com mensagens de erro."],
      ["Estado e testes", "Serviços, RxJS e testes unitários."],
    ],
  },
  {
    id: "vue",
    titulo: "Vue.js na prática",
    area: "Front-end",
    nivel: "Intermediário",
    horas: 45,
    preco: 890,
    img: "./images/c7.jpeg",
    resumo: "Composition API, componentes e consumo de APIs em um projeto completo.",
    ementa: [
      ["Reatividade", "Composition API, refs e computed."],
      ["Componentes", "Props, eventos e slots para interfaces reutilizáveis."],
      ["Rotas e estado", "Vue Router e Pinia em um app de tarefas."],
      ["Projeto final", "Catálogo com busca, filtros e estados de vazio e erro."],
    ],
  },
  {
    id: "carreira",
    titulo: "Carreira tech: portfólio e entrevistas",
    area: "Carreira",
    nivel: "Iniciante",
    horas: 20,
    preco: 390,
    img: "./images/b4.png",
    resumo: "Currículo, LinkedIn, portfólio no GitHub e simulações de entrevista técnica.",
    ementa: [
      ["Currículo e LinkedIn", "Como apresentar projetos e resultados."],
      ["Portfólio no GitHub", "README, organização e projetos que chamam atenção."],
      ["Entrevistas", "Perguntas comportamentais e desafios técnicos."],
      ["Simulação", "Entrevista simulada com feedback individual."],
    ],
  },
];

const POSTS = [
  {
    id: "primeiro-portfolio",
    titulo: "Como montar o seu primeiro portfólio de desenvolvimento",
    data: "2026-08-12",
    autor: "Marina Alves",
    img: "./images/b1.jpg",
    resumo: "Três projetos bem feitos valem mais que dez tutoriais copiados. Veja como escolher e apresentar.",
    corpo: [
      "Recrutadores passam poucos minutos em cada portfólio. Por isso, escolha três projetos que mostrem problemas diferentes resolvidos por você: uma página responsiva, um app com dados de uma API e um projeto com formulário e validação.",
      "Cada projeto precisa de um README com objetivo, tecnologias, prints e o link publicado. Explique uma decisão difícil que você tomou e o que faria diferente.",
      "Por fim, cuide dos detalhes: mensagens de erro claras, estados de carregamento e acessibilidade básica mostram maturidade.",
    ],
  },
  {
    id: "git-sem-medo",
    titulo: "Git sem medo: os comandos que você usa todos os dias",
    data: "2026-07-28",
    autor: "Rafael Costa",
    img: "./images/b2.jpg",
    resumo: "Branch, commit, pull request e como desfazer um erro sem perder o trabalho.",
    corpo: [
      "Comece criando uma branch para cada tarefa. Assim o seu trabalho fica isolado e a revisão fica mais simples.",
      "Faça commits pequenos, com mensagens no imperativo que expliquem o porquê da mudança.",
      "Errou? Use git restore para descartar alterações de um arquivo e git revert para desfazer um commit já publicado sem reescrever o histórico.",
    ],
  },
  {
    id: "python-planilhas",
    titulo: "Troque a planilha manual por um script em Python",
    data: "2026-07-10",
    autor: "Júlia Mendes",
    img: "./images/b3.jpg",
    resumo: "Um exemplo passo a passo para automatizar um relatório semanal com pandas.",
    corpo: [
      "Se você copia e cola os mesmos dados toda semana, um script de 20 linhas pode fazer isso por você.",
      "Com pandas, leia a planilha, filtre o período, agrupe por categoria e exporte o resultado em segundos.",
      "Agende o script e use o tempo livre para analisar os números em vez de montá-los.",
    ],
  },
  {
    id: "ux-mensagens-erro",
    titulo: "Mensagens de erro que ajudam em vez de culpar",
    data: "2026-06-22",
    autor: "Caio Ribeiro",
    img: "./images/b4.png",
    resumo: "Boas mensagens dizem o que aconteceu, por que e como resolver.",
    corpo: [
      "Uma boa mensagem de erro aparece perto do campo, explica o problema em linguagem simples e mostra um exemplo do formato esperado.",
      "Evite culpar a pessoa usuária. Troque \"entrada inválida\" por \"informe um e-mail como nome@dominio.com\".",
      "E não esqueça do sucesso: confirmar que algo deu certo é tão importante quanto avisar do erro.",
    ],
  },
];
/* fim de dados.js */
